"""Weekly LinkedIn outreach digest — Lambda orchestrator."""
import json
import os
import uuid
from datetime import datetime, timezone

import boto3

bedrock_agent = boto3.client("bedrock-agent-runtime")
ses = boto3.client("ses")

AGENT_ID = os.environ["BEDROCK_AGENT_ID"]
ALIAS_ID = os.environ["BEDROCK_AGENT_ALIAS_ID"]
RECIPIENT = os.environ["RECIPIENT_EMAIL"]
SENDER = os.environ["SENDER_EMAIL"]


def invoke_agent() -> str:
    """Invoke Bedrock Agent and collect streamed response."""
    today = datetime.now(timezone.utc).strftime("%B %d, %Y")
    prompt = (
        f"Today is {today}. Search for the latest trending topics in retail strategy, "
        "merchandising, and consumer electronics. Then generate a weekly LinkedIn post "
        "digest with 3-10 post ideas — a mix of full draft posts and topic ideas with "
        "angles and talking points. Return the result as JSON."
    )
    response = bedrock_agent.invoke_agent(
        agentId=AGENT_ID,
        agentAliasId=ALIAS_ID,
        sessionId=str(uuid.uuid4()),
        inputText=prompt,
    )
    chunks = []
    for event in response["completion"]:
        if "chunk" in event:
            chunks.append(event["chunk"]["bytes"].decode("utf-8"))
    return "".join(chunks)


def parse_digest(raw: str) -> dict:
    """Extract JSON from agent response, handling markdown fences."""
    cleaned = raw.strip()
    if "```json" in cleaned:
        cleaned = cleaned.split("```json", 1)[1]
    if "```" in cleaned:
        cleaned = cleaned.split("```", 1)[0]
    try:
        return json.loads(cleaned.strip())
    except json.JSONDecodeError:
        return {"raw_content": raw, "post_ideas": []}


def build_html(digest: dict) -> str:
    """Render digest as an HTML email."""
    date = digest.get("digest_date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    ideas = digest.get("post_ideas", [])

    if not ideas and "raw_content" in digest:
        return f"""<html><body style="font-family:system-ui,sans-serif;max-width:700px;margin:auto;padding:20px">
        <h1>LinkedIn Outreach Digest — {date}</h1>
        <div style="white-space:pre-wrap">{digest['raw_content']}</div>
        </body></html>"""

    cards = []
    for i, idea in enumerate(ideas, 1):
        is_draft = idea.get("type") == "draft"
        badge_color = "#2563eb" if is_draft else "#7c3aed"
        badge_text = "DRAFT" if is_draft else "TOPIC IDEA"
        fmt = idea.get("format", "text_post").replace("_", " ").title()
        tags = " ".join(idea.get("suggested_hashtags", []))

        cards.append(f"""
        <div style="border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin:16px 0">
          <div style="display:flex;align-items:center;gap:8px;margin-bottom:12px">
            <span style="background:{badge_color};color:#fff;padding:2px 10px;border-radius:20px;
                         font-size:12px;font-weight:600">{badge_text}</span>
            <span style="color:#6b7280;font-size:13px">{fmt}</span>
          </div>
          <h3 style="margin:0 0 8px">#{i}: {idea.get('title', 'Untitled')}</h3>
          <div style="background:#f9fafb;border-radius:8px;padding:16px;white-space:pre-wrap;
                      font-size:14px;line-height:1.6">{idea.get('content', '')}</div>
          <div style="margin-top:12px;font-size:13px;color:#6b7280">
            <strong>Source:</strong> {idea.get('source_context', 'N/A')}<br>
            <strong>Why it works:</strong> {idea.get('engagement_angle', 'N/A')}<br>
            {f'<strong>Tags:</strong> {tags}' if tags else ''}
          </div>
        </div>""")

    return f"""<html><body style="font-family:system-ui,sans-serif;max-width:700px;margin:auto;padding:20px">
    <h1 style="border-bottom:3px solid #2563eb;padding-bottom:12px">
      LinkedIn Outreach Digest — {date}
    </h1>
    <p style="color:#6b7280">{len(ideas)} post ideas this week. A mix of ready-to-edit drafts
    and topic ideas with angles you can develop.</p>
    {''.join(cards)}
    <hr style="margin:32px 0;border:none;border-top:1px solid #e5e7eb">
    <p style="color:#9ca3af;font-size:12px">Generated by your LinkedIn Outreach Digest system.
    These are suggestions only — review and personalize before posting.</p>
    </body></html>"""


def send_email(html: str, date_str: str):
    """Send the digest via SES."""
    ses.send_email(
        Source=SENDER,
        Destination={"ToAddresses": [RECIPIENT]},
        Message={
            "Subject": {"Data": f"Your LinkedIn Post Ideas — Week of {date_str}"},
            "Body": {"Html": {"Data": html}},
        },
    )


def lambda_handler(event, context):
    """Entrypoint: invoke agent → parse → format → send."""
    raw = invoke_agent()
    digest = parse_digest(raw)
    date_str = digest.get("digest_date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    html = build_html(digest)
    send_email(html, date_str)
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "Digest sent",
            "date": date_str,
            "post_count": len(digest.get("post_ideas", [])),
        }),
    }
